### ISSUE TITLE
Функция получилась сложной в плане поддержки

### ISSUE THREAD

**Issue by andrey-ilyin** [akimovatatiana/Backend#1]
https://github.com/akimovatatiana/Backend/blob/cd0f68e06f3b1855d896ebfdd792f83624fd3d5b/lw3/PasswordStrength/PasswordStrength/Program.cs#L72

Для каждого правила создайте отдельную функцию.
В результате у вас получится что-то вроде
strength = 0;
strength += GetStrengthForUpperLetters();
strength += GetStrengthForDigits();
...
return strength;

**Comment by akimovatatiana** [comment]
Сделано. Cозданы отдельные функции.

**Comment by andrey-ilyin** [comment]
Принято.
